name: Go test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.6

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
